CREATE TABLE IF NOT EXISTS placement_tests (
  Id BIGINT PRIMARY KEY AUTO_INCREMENT,
  UserId BIGINT NOT NULL,
  TotalScore DECIMAL(6,2) NOT NULL DEFAULT 0,
  LogicScore DECIMAL(6,2) NOT NULL DEFAULT 0,
  ProgrammingScore DECIMAL(6,2) NOT NULL DEFAULT 0,
  OOPScore DECIMAL(6,2) NOT NULL DEFAULT 0,
  WebScore DECIMAL(6,2) NOT NULL DEFAULT 0,
  Level VARCHAR(32) NOT NULL DEFAULT 'pending',
  Strengths JSON,
  Weaknesses JSON,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS skill_profiles (
  Id BIGINT PRIMARY KEY AUTO_INCREMENT,
  UserId BIGINT NOT NULL,
  PlacementTestId BIGINT,
  Level VARCHAR(32) NOT NULL DEFAULT 'pending',
  Strengths JSON,
  Weaknesses JSON,
  RecommendedTopics JSON,
  RecommendedCourseIds JSON,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id),
  FOREIGN KEY (PlacementTestId) REFERENCES placement_tests(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS learning_paths (
  Id BIGINT PRIMARY KEY AUTO_INCREMENT,
  UserId BIGINT NOT NULL,
  RawAIResponse JSON,
  RecommendedCourseIds JSON,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS learning_path_items (
  Id BIGINT PRIMARY KEY AUTO_INCREMENT,
  LearningPathId BIGINT NOT NULL,
  WeekNumber INT NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Description TEXT,
  Topics JSON,
  CourseIds JSON,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (LearningPathId) REFERENCES learning_paths(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS placement_questions (
  Id BIGINT PRIMARY KEY AUTO_INCREMENT,
  UserId BIGINT NOT NULL,
  Question TEXT NOT NULL,
  Options JSON NOT NULL,
  CorrectAnswer VARCHAR(255) NOT NULL,
  Topic VARCHAR(64) NOT NULL,
  BatchId VARCHAR(64),
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS placement_question_bank (
  Id BIGINT PRIMARY KEY AUTO_INCREMENT,
  Topic VARCHAR(64) NOT NULL,
  Question TEXT NOT NULL,
  Options JSON NOT NULL,
  CorrectAnswer VARCHAR(255) NOT NULL,
  Difficulty VARCHAR(64),
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
